sudo: false
language: java

os:
  #not yet available for java - windows 
  - linux
  - osx

git:
  depth: 3
  lfs_skip_smudge: true

jdk:
  - openjdk10
  - openjdk11

services:
  - xvfb

#script: mvn '-Dtest=de.hpi.bpt.scylla.*Tests' test
script:
  mvn clean test

notifications:
  email: false
